[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 9600
monitor_rts = 0
monitor_dtr = 0

; Enable LittleFS filesystem
board_build.filesystem = littlefs

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=1
    -D TINY_GSM_MODEM_SIM7600

lib_deps =
    vshymanskyy/TinyGSM @ ^0.12.0
    knolleary/PubSubClient @ ^2.8
    vshymanskyy/StreamDebugger @ ^1.0.1

    adafruit/Adafruit NeoPixel @ ^1.12.0
    adafruit/Adafruit LIS3DH @ ^1.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14

    bblanchon/ArduinoJson @ ^7.0.4

    arduino-libraries/ArduinoHttpClient @ ^0.6.0